### ISSUE TITLE
Better UI & Harmonization

### ISSUE THREAD

**Issue by ClemCorb** [comejv/ARM-SIM#43]
https://github.com/comejv/ARM-SIM/blob/29d3ba11bf5d221e1098b319ca858a874dc7eea0/test_features.bash#L44C10-L44C10

![image](https://github.com/comejv/ARM-SIM/assets/81227630/3555379e-3fb2-457c-8f1e-273339a7396b)
Double "---", should remove it ?

**Comment by Luminosaa** [comment]
Bof ça marque la fin fin des tests c'est ok
